### ISSUE TITLE
FCS_COP.1(1) Cryptographic Operation (AES Data Encryption/Decryption)

### ISSUE THREAD

**Issue by TForman37** [commoncriteria/wlanaccesssystem#1]
**Comment**
Mandate the entropy requirement be 256 bits, with selection for 128 (Tactical use case) and 192.

Change verbage to include 802.11ax connections.

**Comment by jfisherbah** [comment]
Proposal is to change FCS_COP.1.1/DataEncryption as follows:
a. change cryptographic key sizes line to "cryptographic key sizes **256 bits and** [_**selection:** 128 bits, 192 bits, **no other key sizes**_]"

b. change 802.11ac-2013 reference to 802.11ax-2021.
