### ISSUE TITLE
Appendix A.1 FCS_CKM.2/DISTRIB Cryptographic Key Distribution

### ISSUE THREAD

**Issue by TForman37** [commoncriteria/wlanaccesssystem#10]
**Question for NIAP**
Why did this requirement go from Mandatory to strictly Optional?

**Comment by plughy2** [comment]
FCS_CKM.2/DISTRIB is only applicable when the TOE is distributed (i.e. WLAN Controller and Access Point).  FCS_CKM.2/GTK is still mandatory.

**Comment by jfisherbah** [comment]
Concur with response, believe no action is required here.

**Comment by kgal** [comment]
concur and closing
