### ISSUE TITLE
Evaluation Activity needed for FTP_ITC.1/Client

### ISSUE THREAD

**Issue by kgal** [commoncriteria/wlanaccesssystem#13]

**Comment by macahill** [comment]
Evaluation Activity:

Guidance: 

The evaluator shall review the operational guidance to ensure it contains instructions for configuring the specified frequency band that the TOE is operating on

Test:
The evaluator shall perform the following test:

Test 1: The evaluator shall demonstrate that the TOE can be configured to the specified frequency band
