### ISSUE TITLE
FIA_PSK_EXT.1 TSS Activity

### ISSUE THREAD

**Issue by plughy2** [commoncriteria/wlanaccesssystem#16]
https://github.com/commoncriteria/wlanaccesssystem/blob/1d03c2895184abede504b98228fb4aebe5aba2bb/input/wlanaccesssystem.xml#1653

The following TSS activity for FIA_PSK_EXT.1 needs to be removed:
"For each protocol identified by the requirement, the evaluator shall confirm that the TSS states the conditioning that takes place to transform the text-based pre-shared key from the key sequence entered by the user (e.g., ASCII representation) to the bit string used by the protocol, and that this conditioning is consistent with the last selection in the FIA_PSK_EXT.1.3 requirement."

When the the current/old WLAN PP was created in 2015, the TC agreed to remove the SFR for conditioning.  The reason being, the notion of "conditioning" a PSK using a hash algorithm is a good one, but it's not based on any standard.  If you do this conditioning of keys, you'll have interoperability between different IPsec peers unless they both happen to support exactly the same type of conditioning.   While the conditioning SFR was removed, unfortunately this TSS activity was erroneously left in and resulted in consistent confusion with the test labs.  The paragraph needs to be removed.

**Comment by kgal** [comment]
I incorporated the recommendation given. Since there has been no negative feedback since then, I am closing this issue.
