### ISSUE TITLE
EAs for FTP_ITC.1

### ISSUE THREAD

**Issue by plughy2** [commoncriteria/wlanaccesssystem#17]
https://github.com/commoncriteria/wlanaccesssystem/blob/1d03c2895184abede504b98228fb4aebe5aba2bb/input/wlanaccesssystem.xml#L643

With the move of wireless client communications to FTP_ITC.1/Client, the evaluation activities for FTP_ITC.1 are not in addition to those required by the NDcPP.  Rather they are the same as the NDcPP.  Since they are now redundant, suggest this whole section simply say "Refer to the EAs for FTP_ITC_EXT.1 in the NDcPP."

**Comment by kgal** [comment]
I have incorporated the recommendations given. Since there has been no negative feedback since the changes were made, I am closing this issue.
