### ISSUE TITLE
WPA2-Enterprise in FTP_ITC.1.1/Client

### ISSUE THREAD

**Issue by plughy2** [commoncriteria/wlanaccesssystem#18]
https://github.com/commoncriteria/wlanaccesssystem/blob/1d03c2895184abede504b98228fb4aebe5aba2bb/input/wlanaccesssystem.xml#L1288

Consistent with the PP Module for wireless clients, FTP_ITC.1.1/Client should specify WPA2-Enterprise as an optional selection and not mandated one.

**Comment by kgal** [comment]
I do not believe WPA2-Enterprise being optional changes this the module significantly---support for WPA2-Enterprise is going to be ubiquitous on WLAN AP in the near future, so I have decided not to make it optional. APs need to support more protocols than clients, so I do not think it needs to be consistent with the client module.
