### ISSUE TITLE
The negotiation "down" from an IKEv2 to IKEv1 exchange

### ISSUE THREAD

**Issue by plughy2** [commoncriteria/wlanaccesssystem#19]
https://github.com/commoncriteria/wlanaccesssystem/blob/1d03c2895184abede504b98228fb4aebe5aba2bb/input/wlanaccesssystem.xml#L739

The negotiation "down" from an IKEv2 to IKEv1 exchange is not a security functional requirement (SFR) of IKEv2 and nor should it be.  It follows that this audit requirement should be designated as conditional at best, or outright removed.

**Comment by kgal** [comment]
I have incorporated the recommendation given. Since no negative feedback was issued on this revision, I am closing this issue.
