### ISSUE TITLE
Update of IEEE Standard to 802.11-2016

### ISSUE THREAD

**Issue by TForman37** [commoncriteria/wlanaccesssystem#3]
**We are looking to update the following modules to reflect the new standard:**
_FCS_COP.1(1)_
_FTP_ITC.1 Inter-TSF Trusted Channel_
_FCS_CKM.1/WPA Cryptographic Key Generation (Symmetric Keys for WPA2 Connections)_
_FCS_CKM.2/GTK Cryptographic Key Distribution (GTK)_
_FCS_CKM.2/PMK Cryptographic Key Distribution (PMK)_

**Comment by jfisherbah** [comment]
Proposed change is to update all 802.11-2012 references globally to 802.11-2020.
