### ISSUE TITLE
FCS_CKM.2 GTK/PMK

### ISSUE THREAD

**Issue by TForman37** [commoncriteria/wlanaccesssystem#4]
**Comment**
_FCS_CKM.2/PMK_ should include support for WPA3-Enterprise.

**Auditable Events**
Key management systems should be audited to check for compliance.

**Comment by jfisherbah** [comment]
Proposed change is to update the FCS_CKM.2/PMK application note as follows:
* current: "The intent is that any WLAN AS evaluated against this PP-Module will support WPA2-ENT..."
* proposed: "The intent is that any WLAN AS evaluated against this PP-Module will support both WPA2-Enterprise and WPA3-Enterprise at minimum..."
