### ISSUE TITLE
FIA_8021X_EXT.1 Extended: 802.1X Port Access Entity Authentication

### ISSUE THREAD

**Issue by TForman37** [commoncriteria/wlanaccesssystem#5]
**Auditable Events**
Authentication failure should be auditable.

**Comment by jfisherbah** [comment]
Proposal is to add auditable event for "Failed authentication attempt" for an FIA_8021X_EXT.1 row in the auditable events table, with "Provided client identity (e.g. MAC address)" for the Additional Audit Record Contents.
