### ISSUE TITLE
FIA_UAU.6 Re-authenticating

### ISSUE THREAD

**Issue by TForman37** [commoncriteria/wlanaccesssystem#6]
**Auditable Events**
Administrative user password changes.

**Comment by jfisherbah** [comment]
Proposal is to take no action - this Module only extends NDcPP and NDcPP has an auditable event for resetting an administrator password. 

This could be revisited in the future if the WLAN AS Module is ever modified to extend other Base-PPs that may not already have that auditable event.

**Comment by kgal** [comment]
Proposal was to take no action and no action was taken (so closing).
