### ISSUE TITLE
FIA_PSK_EXT.1 Extened: Pre-Shared Key Composition

### ISSUE THREAD

**Issue by TForman37** [commoncriteria/wlanaccesssystem#7]
**Comment**
Verbiage should reflect the ability to support WPA3-SAE (192 bit key size), WPA3-Enterprise (Suite B, 256).

**Comment by jfisherbah** [comment]
Proposed response is to add "WPA3-SAE" as selectable option to FIA_PSK_EXT.1.1. 

SAE replaces WPA2-PSK if used, but part of establishing the WPA3-SAE connection technically uses a pre-shared key, so it is proposed that no change to the app note or EA needs to be made to add support for this.

**Comment by kgal** [comment]
The original comment said mentioned WPA3-SAE and WPA-Enterprise. The proposed response only mentioned WPA3-SAE. Is this correct?

**Comment by macahill** [comment]
> The original comment said mentioned WPA3-SAE and WPA-Enterprise. The proposed response only mentioned WPA3-SAE. Is this correct?

Yes this is correct.  WPA3-Enterprise doesn't use a PSK to authenticate so should not have fell under FIA_PSK_EXT.1 to begin with.

**Comment by kgal** [comment]
As there has been no dissent, I am closing this issue.
