### ISSUE TITLE
FMT_SMR.1 Security Management Roles

### ISSUE THREAD

**Issue by TForman37** [commoncriteria/wlanaccesssystem#8]
**Auditable Events**
Remote administrative action.

**Comment by jfisherbah** [comment]
Proposal is to take no action - this Module only extends NDcPP and NDcPP already has an auditable event for all administrative actions.

This could be revisited in the future if the Module is ever modified to allow other Base-PPs that do not already have the same requirement.

**Comment by jfisherbah** [comment]
A new comment was issued on the topic of management functionality to request an update to allow the management function of configuring the frequency band, including 6 GHz to support Wi-Fi 6E. 

The proposed response to this is as follows:
a. Add new SFR: FMT_SMF.1/AccessSystem

FMT_SMF.1.1/AccessSystem The TSF shall be capable of performing the following management functions: [_set allowed wireless frequency band to [**selection:** 2.4 GHz, 5 GHz, 6 GHz]_].

b. Map new SFR to O.TOE_ADMINISTRATION with the following rationale: FMT_SMF.1/AccessSystem supports the objective by defining management functionality that is specific to WLAN Access System devices.

c. Map new SFR to Base-PP consistency rationale with the following rationale: This SFR defines additional management functionality that is specific to the Module’s product type and would therefore not be expected to be present in the Base-PP.
